### ISSUE TITLE
Swelvy BG goes away after clicking Apply Button

### ISSUE THREAD

**Issue by Naxrin** [OmgRod/Geodify#10]
after i click the apply button in PackSelectLayer of texture loader, it reloads texture and return to the raw PackSelectLayer, is it practicial that swelvyBG is still there after apply button clicked?

**Comment by OmgRod** [comment]
Hi. I am currently trying to implement a fix for this but so far it doesn't work. In the meantime, you can try to fix it with instructions on https://github.com/OmgRod/Geodify/blob/master/README.md

Sorry for the inconvenience.

**Comment by Naxrin** [comment]
Got a super oddity solution
```
#include <Geode/modify/CCSprite.hpp>
class $modify(CCSprite) {
    void draw() {
        CCSprite::draw();
        auto scene = CCDirector::sharedDirector()->getRunningScene();
        if (auto pkl = scene->getChildByID("PackSelectLayer")) {
            if (auto bg = pkl->getChildByID("background"))
                bg->setVisible(false);
            
            if (pkl->getChildByID("swelvy-background"))
                return;

            SwelvyBG* swelvyBG = SwelvyBG::create();
            swelvyBG->setZOrder(-1);
            swelvyBG->setID("swelvy-background");
            pkl->addChild(swelvyBG);
        }
    }
};
```
This does solve the apply button issue, but the price is to check pack select layer each time the game draw a CCSprite. Not sure how severely it would affect low end device on level gameplay(?) so im not certain it deserves or not
