### ISSUE TITLE
Missed a spot

### ISSUE THREAD

**Issue by Vaulto350** [OmgRod/Geodify#6]
You missed the list UI 

![image](https://github.com/OmgRod/Geodify/assets/170834314/a5be1bfc-9c70-4384-9ddf-fece69e5e328)

> Screenshot taken using v1.0.1

**Comment by OmgRod** [comment]
Hi. Sorry for not replying! This seems to be a bug as this seems to work in v1.1.0. Did you open this menu from the lists tab or from somewhere else?
